sudo: required
services:
  - docker

before_install:
  - docker build -t bmonsterman/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true bmonsterman/react-test npm run test -- --coverage

after_success: 
  - docker build -t bmonsterman/fib-calc-client ./client
  - docker build -t bmonsterman/fib-calc-nginx ./nginx
  - docker build -t bmonsterman/fib-calc-server ./server
  - docker build -t bmonsterman/fib-calc-worker ./worker

# Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push bmonsterman/fib-calc-client
  - docker push bmonsterman/fib-calc-nginx
  - docker push bmonsterman/fib-calc-server
  - docker push bmonsterman/fib-calc-worker

  deploy:
    provider: elasticbeanstalk
    region: 'us-east-2'
    app: 'fib-calc'
    env: 'Fibcalc-env'
    bucket_name: 'elasticbeanstalk-us-east-2-400078757370'
    bucket_path: 'fib-calc'
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY